services:
  - type: web
    name: tambuy
    env: python
    buildCommand: |
      mkdir -p /opt/render/project/src/database
      cp database/database-table-badc5-firebase-adminsdk-fbsvc-fee7cfa592.json /opt/render/project/src/database/
      pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
    staticPublishPath: ./staticfiles
    autoDeploy: true
